version: "3.8"

services:
  redis:
    image: redis:7
    container_name: rate_limiter_redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate_limiter_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
